[tool.ruff]
line-length = 100
fix = true
exclude = [".venv", "migrations", "__pycache__", "*.pyc"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501", "F403", "F405", "C408"]  # C408 отключает навязывание frozenset, чтобы не трогать логику

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true
