name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # НИКАКИХ docker system prune здесь, на раннере!

      - name: Deploy via SSH (git pull + docker compose)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd "${SERVER_PATH:-/root/bots/kbju_bot}"

            echo ">>> Git sync"
            git fetch origin
            git reset --hard origin/main

            echo ">>> Server cleanup (safe)"
            docker image prune -f || true
            docker builder prune -af || true
            docker system prune -af --volumes || true

            echo ">>> Build & up"
            docker compose pull || true
            docker compose build bot     # без --no-cache
            docker compose up -d

            echo ">>> Post-clean (dangling layers)"
            docker image prune -f || true

            echo ">>> Status"
            docker compose ps
            docker compose logs -n 50 bot || true
